X00TD: Enforce user libs at build time
error: mismatch in the <uses-library> tags between the build system and the manifest:
	- required libraries in build system: []
	                 vs. in the manifest: [qcom.fmradio]
	- optional libraries in build system: []
	                 vs. in the manifest: []
	- tags in the manifest (/home/cirrus/roms/CherishOS-twelve/out/soong/.intermediates/vendor/qcom/opensource/fm-commonsys/fmapp2/FM2/android_common/manifest_fixer/AndroidManifest.xml):
		<uses-library android:name="qcom.fmradio" android:required="true"/>
note: the following options are available:
	- to temporarily disable the check on command line, rebuild with RELAX_USES_LIBRARY_CHECK=true (this will set compiler filter "verify" and disable AOT-compilation in dexpreopt)
	- to temporarily disable the check for the whole product, set PRODUCT_BROKEN_VERIFY_USES_LIBRARIES := true in the product makefiles
	- to fix the check, make build system properties coherent with the manifest
	- see build/make/Changes.md for details